### ISSUE TITLE
Can I use view::composer ?

### ISSUE THREAD

**Issue by domeinznl** [PhiloNL/Laravel-Blade#12]
Does anybody now I can call the view composer ?

I try to run : 
```php
$this->blade->view()->composer('file');
```

Now I get this error : 
Warning: Missing argument 2 for Illuminate\View\Factory::composer(), called in

How can I fix this ?

**Comment by PhiloNL** [comment]
I think this should work:

```php
        View::composer('dashboard', function($view)
        {
             $this->blade->view()->composer('file', function($view) {
                   $view->with('something', 'value');
             });
        });
```

**Comment by domeinznl** [comment]
it is working but I dont get the view on my main view.

**Comment by PhiloNL** [comment]
Not sure what you mean? What are you trying to achieve?

**Comment by domeinznl** [comment]
Well I am trying to get a "modular" block view inside my main view.
And somebody on laravel.io advised to try use view::composer.

When I call your code ( I dont get an error) but i dont see the view that I am requesting.
So maybe I should make a custom blade function that will let me call the "block" controller and get the view.

**Comment by PhiloNL** [comment]
Could you post some code with the expected result?
You are aware that view::composer is just a method to set certain variables when a specific blade template is called?

**Comment by domeinznl** [comment]
Welcome controller which call the welcome view : 
```php
<?php if (!defined('FLEX') or !constant('FLEX')) die('Direct access not allowed!');
/**
* @filesource Application/Controllers/Welcome.php
* @namespace none
* @author Wouter van Marrum
* @package FlexorCMS
* @copyright 2014 (c) All Rights Reserved.
* @version v0.1
*/

class Welcome extends BaseController {

	public function __construct() {
		$auth = new Auth();
	}
	
	public function index() {

		$this->template()->make('welcome');
	}
}
```

welcome view : 
```blade
@extends('_base')

@section('title') Welkom ! @stop

@section('content')

<div class="container">
	<div class="welcome--top">
		<div class="row z-depth-1">
			<header class="col s12 red accent-1">
				<h2 class="center-align">FlexorCMS</h2>
			</header>
			<article class="col s12 blue-grey lighten-5">
			<p>This page dynamically generated by FlexorCMS.</p>

			<p>If you would like to edit this page you'll find it located at:</p>
				<pre><code class="language-markup">Application/Views/welcome.blade.php</code></pre>

			<p>The corresponding controller for this page is found at:</p>
				<pre><code class="language-markup">Application/Controllers/Welcome.php</code></pre>

			<p>If this is the first time that you are using FlexorCMS, you should start by reading our 
			{{ HTML::Anchor(Routes::generate('http://www.concept-core.nl/flexor/help/'), 'user guide', array('class'=>'btn grey darken-4 waves-effect waves-light')) }}
			</p>
			</article>
		</div>
	</div>
</div>

@stop
```

Base view : 
``blade
<!DOCTYPE html>
<html>
	<head>

		{!! Theme::headerBar(); !!} 
		

		
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
		
		
		<meta name="theme-color" content="#ffcdd2">
		
		
		<link rel="stylesheet" href="{{BASE_URL}}/{{PUB}}Flexor/css/style.css" media="screen">
		<link rel="stylesheet" href="{{BASE_URL}}/{{PUB}}Flexor/css/prism.css">
		
		<link type="text/css" rel="stylesheet" href="{{BASE_URL}}/{{PUB}}materialize/css/materialize.min.css"  media="screen,projection"/>
		<link href="http://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet" type="text/css">
	</head>
	<body class="grey lighten-5">
		@yield('content')

		
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="{{BASE_URL}}/{{PUB}}Flexor/js/prism.js"></script>
		<script type="text/javascript" src="{{BASE_URL}}/{{PUB}}materialize/js/materialize.min.js"></script>
	</body>
</html>
```

Theme class : 
```php
<?php if (!defined('FLEX') or !constant('FLEX')) die('Direct access not allowed!');
/**
* @filesource /C/xampp/htdocs/wouter/flexCMS/System/Blocks/Flexor/theme.php
* @namespace none
* @author Wouter van Marrum
* @package FlexorCMS
* @copyright 2014 (c) All Rights Reserved.
* @version v0.1
* @category Block
*/

/**
* Flexor theme Block
*/
class Theme extends BaseController {

	public static $viewFolder = "Flexor.";
	
	public static function headerBar() {
		$data = array(
			1 => "welcome",
			2 => "my", 
			3 => "world!"
		);

		$view = New BaseView();
		$view->blade->view()->composer(self::$viewFolder.'headerBar', function($v) {
		     $v->with('data', $data);
		});
	}
}
```

headerbar view : 
```blade
<title>@yield('title')</title>
<meta name="description" content="@yield('description')">
```

**Comment by PhiloNL** [comment]
That won't work. You are creating a new blade instance when you call headerBar.
You need to make sure you use the same instance. Laravel for example has a container containing all instances. http://laravel.com/docs/5.0/container

**Comment by domeinznl** [comment]
ok thats explains a lot.
But I also have made a custom blade function trying to use the $__env variable but it doesn't work.
Want to see an example from that to ?
