### ISSUE TITLE
extend does not work

### ISSUE THREAD

**Issue by djboy** [PhiloNL/Laravel-Blade#18]
Hi,
I tried to use extend
like so

Blade::extend(function($value)
{
  return preg_replace('/(\s*)@(break|continue)(\s*)/', '$1<?php $2; ?>$3', $value);
});

I get 
 Call to undefined method Philo\Blade\Blade::extend()
Thank you.

**Comment by PhiloNL** [comment]
https://github.com/PhiloNL/Laravel-Blade/issues/6
