### ISSUE TITLE
Problem using $this in view

### ISSUE THREAD

**Issue by Patroklo** [PhiloNL/Laravel-Blade#21]
Hi, I'm trying to use the $this variable in a view using the Blade layout. I have already made a `with('this', $viewObject)->` calling and when I make a var_dump of the $this variable it works just fine and says that it's the view object. But the moment I try to call any method inside it, launches the error `Call to undefined method Illuminate\View\Engines\CompilerEngine::methodName()` 

Am I doing anything wrong?

**Comment by PhiloNL** [comment]
I would recommend using a different key for defining the object.
