### ISSUE TITLE
Cache files and git

### ISSUE THREAD

**Issue by sjosen** [PhiloNL/Laravel-Blade#37]
Hello,

I've been using this for some time now and it has been working fine for me. I have a production and a development environment and using git branches for these. 
Now suddenly I'm having issues with the blade cache files between these branches. How should these files be handled with git? Should the files be ignored og created directly on production or should I track them with git from the development?
Also when are these files regenerated in Blade?

Thanks in advance

**Comment by ghost** [comment]
The template cache files are regenerated when you delete them all manually.

**Comment by PhiloNL** [comment]
These files should be ignored, do not include them in your version control.

**Comment by sjosen** [comment]
Thanks guys - much appreciated
