### ISSUE TITLE
Can't use blade extend

### ISSUE THREAD

**Issue by ghost** [PhiloNL/Laravel-Blade#6]
I came across a problem today.
Wanted to extend blade so I can assign variables in the templates them self but It gave me the following error : "Call to undefined method Illuminate\View\Factory::extend()"

Is there someone who knows how to fix this ?
Greets Wouter.

**Comment by ekandreas** [comment]
Think this is deprecated with 5.1...
Use directive instead?

```php		
		$blade->getCompiler()->directive( 'hello', function( $expression )
		{
			$expression = preg_replace( '#\((.*)\)#', '$1', $expression );
		    return "<?php echo '$expression'; ?>";
		});
```
