### ISSUE TITLE
Support for 5.0?

### ISSUE THREAD

**Issue by squidge** [PhiloNL/Laravel-Blade#9]
Hi,

Any plans to align to illuminate/view 5.0?

**Comment by VerifiedToken** [comment]
Hey,

I'm wondering about this as well. Any news?

**Comment by squidge** [comment]
@VerifiedToken It is not difficult at all to upgrade it actually, just bumped the version number and all still works

**Comment by VerifiedToken** [comment]
Ah! I'll give that a go. Thanks @squidge

**Comment by frostymarvelous** [comment]
But it would be ideal if this were done I'm the actual repo. 

@squidge did you clone it or you bumped in your composer?

**Comment by frostymarvelous** [comment]
Found this https://getcomposer.org/doc/articles/troubleshooting.md#need-to-override-a-package-version

**Comment by PhiloNL** [comment]
Now using L5. https://github.com/PhiloNL/Laravel-Blade/commit/e496786a5523669e64e0e8feb1f9be7e7ef513c8

**Comment by visavi** [comment]
after updating to 2.2 displays an error Class 'Illuminate\Events\Dispatcher' not found

**Comment by visavi** [comment]
add composer.json  string "illuminate/events": "~5"

**Comment by PhiloNL** [comment]
@visavi Done!

**Comment by visavi** [comment]
probably more correct to specify the version ~5.0 because it is possible in 5.1 that will change
example https://github.com/laravel/framework/blob/5.0/composer.json

and look at my pull request there is a useful correction  https://github.com/PhiloNL/Laravel-Blade/pull/10
